### ISSUE TITLE
ActionMailer::Preview

### ISSUE THREAD

**Issue by kaluznyo** [fphilipe/premailer-rails#100]
Hi,

I trying to use ActionMailer::Preview with rails 4.1.beta1.

FYI : Integration of https://github.com/37signals/mail_view into rails.
(http://edgeapi.rubyonrails.org/classes/ActionMailer/Base.html)

After add previewing email into my app. The view is rendering into an iframe. But the CSS is added as a link css, but not inline. Any chance to force call to premailer, or best, integration with this ? Thanks !

**Comment by anduong** [comment]
@fphilipe: How's the discussion going?
