### ISSUE TITLE
Pointing to Full application.scss & Including Twitter Bootstrap

### ISSUE THREAD

**Issue by kimardenmiller** [fphilipe/premailer-rails#107]
Following the idea of object-oriented programming, it seemed to make sense to me to include my entire site's existing css to have at my disposal when composing emails. It worked, except for the inclusion of Bootstrap 3, which seemed to add many mixins with ! Important that over rode my other CSS:

```
    <div class="sv-logo" href="/landing" style="-moz-box-sizing: border-box; -webkit-box-sizing: border-box; background-color: transparent !important; box-shadow: none !important; box-sizing: border-box; color: #000 !important; font-family: 'Yanone Kaffeesatz', sans-serif; font-size: 2.1em; font-weight: 600; letter-spacing: -1px; text-decoration: none; text-shadow: none !important">
      <span class="spoken" style="-moz-box-sizing: border-box; -webkit-box-sizing: border-box; background-color: transparent !important; box-shadow: none !important; box-sizing: border-box; color: #000 !important; text-shadow: none !important">
```

Is it totally a mis-use of Premailer to try that?

Is there something in Premailer that compiled Bootstrap to create these issues that are not a problem on the website itself with the same CSS?  Such as:

```
box-sizing: border-box; color: #000 !important;
```

**Comment by nragaz** [comment]
In case someone finds this in the future -- this appears to be an issue with using hpricot specifically. For whatever reason, the styles from Bootstrap's vendor-prefixed mixins (like box-sizing, and placeholder color) are getting applied to *every* element. Switching to nokogiri fixes this.
