### ISSUE TITLE
Removes Script Tags

### ISSUE THREAD

**Issue by parterburn** [fphilipe/premailer-rails#120]
I'm trying to add [Schema Markup](https://developers.google.com/gmail/actions/reference/go-to-action) to my emails, but it looks like premailer is removing the script tag and everything in it.

Is there an option to disable that?

**Comment by bartoszkopinski** [comment]
Wow, took me a while to find a reason for disappearing `script` tags.

@fphilipe You should perhaps add this to the readme (maybe even the full configuration sample). This is rather unexpected behaviour for something that should handle the CSS only and there is not a single mention of (java)script (same in the premailer readme).

**Comment by fphilipe** [comment]
@bartoszkopinski PR welcome :blush:
