### ISSUE TITLE
latest Premailer is not inlining css with rails 4.1.5

### ISSUE THREAD

**Issue by mankind** [fphilipe/premailer-rails#124]
First  thanks for the premailer-rails gem. I have a situation where I am storing email templates in the database and so i am sending html email without using a template file. Premailer-rails does not  inline the css unless there is a template file.  It does not even use the css, so the colours are unchanged. Premailer is not working for the use case of storing emails in the database. 

 Is there a way to get this working?

     class TemplateMailer < ActionMailer::Base

        mail( 
                  :subject => email_template.subject,
                   :recipients => email_template.to,
                    :from => email_template.from,
                    :body => email_template.body,
                    :content_type => "text/html"
           )
     end

An example of email template the body is this:

     <!DOCTYPE html>
     <html>
        <head>
           <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' >
            <%= stylesheet_link_tag ("email") %>
       </head>
        <body>
           <p class="cheese">Thanks for indicating interest! </p>
           <p class="title"> {{name}} {{joy}}</P>
        </body>
       </html>

The css file in app/assets/stylesheets/email.cs

             .cheese {  color: blue; }
             .title { color: red;}

Someone had a similar issue discussed in https://github.com/premailer/premailer/issues/3
The solution was to do:

        premailer = Premailer.new('<p>test</p>', :with_html_string => true).

But premailer-rails  already has that set to true as shown in the links below. So why is loading html from the database not working 

https://github.com/fphilipe/premailer-rails/blob/92911501de7cfae47081b083369ddcd5c2869494/spec/unit/customized_premailer_spec.rb#L65

https://github.com/fphilipe/premailer-rails/blob/92911501de7cfae47081b083369ddcd5c2869494/lib/premailer/rails/customized_premailer.rb#L9

**Comment by fphilipe** [comment]
The CSS is only inlined once `message.deliver` is called. At that point the ActionMailer will call the hook (`#delivering_email`).
