### ISSUE TITLE
Inline css in views (not in email)

### ISSUE THREAD

**Issue by mmustala** [fphilipe/premailer-rails#136]
Hi,

Would it be possible to use css inlining in normal rails view?

My app is generating views that can be included into other sites and sometimes the styles in the other site are doing nasty things for the view. If I inline the css in my view I think most of these problems could be avoided.

**Comment by fphilipe** [comment]
Theoretically, yes. Take a look at premailer which is used under the hood (this is just an adapter for rails.)
