### ISSUE TITLE
Error when preview the email if action_controller.asset_host  with port 

### ISSUE THREAD

**Issue by songjiayang** [fphilipe/premailer-rails#138]
1. In development, asset_host = 'localhost:3000' ,
2. include my css with `<%= stylesheet_link_tag :email%>`
3.  visit the preview url  get some errros 
![screen shot 2015-04-18 at 2 36 14 pm](https://cloud.githubusercontent.com/assets/1459834/7214318/5953f544-e5d9-11e4-8a1f-2eb093b8997b.png)

I find the error about code, https://github.com/fphilipe/premailer-rails/blob/master/lib/premailer/rails/css_loaders/network_loader.rb#L20
but i am not find a elegant way to fix it.

**Comment by fphilipe** [comment]
Why do you specify your asset host at all in development?

**Comment by bkroeker** [comment]
I'm running into exactly this problem too.  I had to specify the asset host in development because it threw an error if I left it blank:

```
NoMethodError: undefined method `split' for nil:NilClass
from /Users/bkroeker/.rvm/gems/ruby-2.2.0@greenbelt/gems/premailer-rails-1.8.0/lib/premailer/rails/css_loaders/network_loader.rb:17:in `uri_for_url'
```

**Comment by bonkydog** [comment]
premailer-rails (v1.8.0) crashes on line 17 of network_loader.rb unless asset_host is set.
