### ISSUE TITLE
Partial markup gets wrapped with <html>,<head> and <body>

### ISSUE THREAD

**Issue by crtvhd** [fphilipe/premailer-rails#141]
I am using premailer to inline css my e-mail partials that look like this:
```html
<style>
  .foo { display: block }
</style>
<table>
[…]
</table>
```

After running ```Premailer.new("<style>…</style><table>…</table>", with_html_string: true).to_inline_css```, I always end up with a complete html skeleton: doctype, html, body and head tags which I do not need. Is there any way to prevent this behaviour?

**Comment by fphilipe** [comment]
I doubt it. But you can ask over at premailer. My gem merely loads the CSS and passes it to premailer, similarly to how you're doing above.
