### ISSUE TITLE
Provide setting to skip premailer in test environments 

### ISSUE THREAD

**Issue by hooptie45** [fphilipe/premailer-rails#143]
I want to disable the Premailer globally as part of my test configuration. But it seams like the only way to disable the premailer is to use the skip_premailer option on the `#mail` call. Can we support this option on the Premailer::Rails.config?

**Comment by fphilipe** [comment]
How about not including the gem in your test group?

**Comment by heatherpike** [comment]
I have a similar issue. I would like to disable premailer in my test environment, and although excluding the gem from the test group works to do that, I also want to configure Premailer options with preserve styles set to true. However, when I include this in an initializer file, it breaks all of my tests. I'd like to instead configure this option in my config/environment files for development and production. 

How might I go about this? I wanted to do something like Premailer.config[:preserve_styles] = true, but there is no config method on Premailer. Thanks in advance!

**Comment by MatheusRich** [comment]
Any workaround for this?
