### ISSUE TITLE
undefined method `find_asset' for nil:NilClass in asset_pipeline_loader

### ISSUE THREAD

**Issue by javierjulio** [fphilipe/premailer-rails#145]
Today I updated the sprockets-rails gem which is now at 3.0.0 and noticed an error occurring after updating: "NoMethodError·undefined method `find_asset' for nil:NilClass". I'm using latest premailer-rails 1.8.2. The error is is happening here: https://github.com/fphilipe/premailer-rails/blob/master/lib/premailer/rails/css_loaders/asset_pipeline_loader.rb#L10

Noticed the issue reported on sprockets-rails https://github.com/rails/sprockets-rails/issues/237 back in April for the 3.0 version. I didn't see what the fix was but it was mentioned that it was resolved in react-rails. I figure the same issue that happened there is probably happening here.

**Comment by javierjulio** [comment]
It seems the OP at https://github.com/rails/sprockets-rails/issues/237 also posted about it at: https://github.com/reactjs/react-rails/pull/241 I haven't been able to look into this yet as I need to revert back but wanted to mention the issue while I noticed it and had all this info.

**Comment by fphilipe** [comment]
Thanks for reporting. Does this error pop up only in production or also in development? I'm currently not using this gem and thus haven't come across this.

I guess the fix would be to augment the check in [`asset_pipeline_present?`](https://github.com/fphilipe/premailer-rails/blob/e0494b0a346879db649f20c4efd35f84596783dc/lib/premailer/rails/css_loaders/asset_pipeline_loader.rb#L15-L17) so that it returns `false` in that case. I'm happy to accept a PR :wink:

**Comment by stevestmartin** [comment]
I am experiencing this issue in production and wasn't able to reproduce it in development. I haven't had time to write a pull request with proper tests and to maintain compatibility with sprockets 2, I do have a branch as a work around that is working for us in production if anyone else needs an immediate fix or needs a starting point to a more proper fix.

https://github.com/stevestmartin/premailer-rails/tree/sprockets3

**Comment by jnimety** [comment]
`sprockets-rails` no longer sets `Rails.application.assets` if `Rails.application.config.assets.compile` is `false` (https://github.com/rails/sprockets-rails/issues/294).  I'm having early success in production by simply setting `Rails.application.config.assets.compile = true`.  We use a CDN, so this isn't strictly necessary, but it lets `premailer-rails` use assets in production.

**Comment by DannyBen** [comment]
Thanks for the quick fix. Just came here with the same issue (production only), saw it was fixed, updated the gem to 1.9.0 (was 1.8.2) and it seems to be ok.

**Comment by glebm** [comment]
This fix makes still makes it so the assets can no longer be found in production. Looking at https://github.com/rails/sprockets-rails/issues/311, it seem this gem should use `Rails.application.assets_manifest.assets[filename]` to get the correct path to the compiled.

For now worked around like this in my email template:

```slim
link href="/assets/#{assets_manifest.assets['email.css']}" rel='stylesheet' type='text/css'
```

**Comment by fphilipe** [comment]
@glebm `::Rails.application.assets_manifest.assets[filename]` should be used instead of `::Rails.application.assets.find_asset(file)`?

**Comment by glebm** [comment]
@fphilipe It should use `assets_manifest.assets[filename]` but only if `config.assets.compile` is false (i.e. the assets have been precompiled). If the `config.assets.compile` is true, it should use a path such as  `/assets/filename.css`.

**Comment by DannyBen** [comment]
Maybe this helps?
```
def asset_exist?(path)
  if Rails.configuration.assets.compile
    Rails.application.precompiled_assets.include? path
  else
    Rails.application.assets_manifest.assets[path].present?
  end
end
```

**Comment by glebm** [comment]
@DannyBen That may incorrectly report true if an asset has been precompiled, but then removed. I don't think premailer-rails should attempt to use precompiled assets if `compile` is true, as that may result in using older versions of assets or assets that no longer exist.

**Comment by glebm** [comment]
Seeing as this is still an issue, can this be re-opened?

**Comment by fphilipe** [comment]
@glebm

> Still broken! This fix makes it so the assets can no longer be found in production. Looking at https://github.com/rails/sprockets-rails/issues/311, it seem this gem should use `Rails.application.assets_manifest.assets[filename]` to get the correct path to the compiled file in production.
>
> A workaround for now (in the email template), works correctly in production and development:
>
> ```slim
> link[rel='stylesheet' type='text/css'
>   href="/assets/#{Rails.application.config.assets.compile ? 'email.css' : assets_manifest.assets['email.css']}"]
>
> ```

I've looked further into this issue. I don't understand why anyone would want to use the asset pipeline in production. Why don't you simply use [`stylesheet_link_tag`](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-stylesheet_link_tag), which takes care of this? Then premailer-rails will find your CSS in either `public/assets` or, if you have them on a CDN, request it. Am I missing something?

**Comment by javierjulio** [comment]
@fphilipe yes I believe what you're missing is that this happens with `stylesheet_link_tag`. I'm using that to link to a SASS file in my email layout that caused the error I reported. This is what I specify in my email layout file:

```erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width"/>
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet" type="text/css" />
<%= stylesheet_link_tag 'email' %>
<style type="text/css" data-premailer="ignore">
@media only screen and (max-width: 596px) {
```

**Comment by fphilipe** [comment]
@javierjulio I don't follow.

As far as I can tell, in development it will pick up the asset from the asset pipeline.

In production the asset pipeline won't be available ([this](https://github.com/fphilipe/premailer-rails/blob/cd21bbb325790289dc3ac49b05ba178e9cc11839/lib/premailer/rails/css_loaders/asset_pipeline_loader.rb#L15-L19) will be `nil`) and thus, it will look for the compiled asset in `public/`. Since rails' `stylesheet_link_tag` will output something like `http://www.example.com/assets/email-fingerprint.css`, it will look for `public/assets/email-fingerprint.css`. If it can't find that (e.g. when you don't have the compiled assets in the app, but on a CDN), it will request `http://www.example.com/assets/email-fingerprint.css`.

Are you using the asset pipeline in production?

**Comment by glebm** [comment]
@fphilipe In production when using a CDN such as CloudFront, it should pull the local file instead of making a network request to CloudFront. So the following order:

1. `Rails.application.config.assets.compile` is true => `email.css`.
2. Otherwise, `assets_manifest.assets['email.css']`.
3. Only if 2 is nil, fall back to making a request.

**Comment by fphilipe** [comment]
But `stylesheet_link_tag` will output the fingerprinted file name, which happens to be `assets_manifest.assets['email.css']`. It will look that file up in `public/` and thus not make a request.

@glebm Are you saying that it should use the asset pipeline strategy in production? I think it's not considered good practice to have that enabled as it is rather slow. Maybe I'm misunderstanding what you mean in point 2. Can you elaborate?

**Comment by javierjulio** [comment]
@fphilipe I have to be honest, I'm not entirely sure how it all works under the hood. I went with this approach as its what I expect with Rails as if I were in a normal browser requested view. I did forget to point out that I do specify my email stylesheet in the config/initializers/assets.rb:

```ruby
# ...
# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
Rails.application.config.assets.precompile += %w(
  email.css
)
```

**Comment by glebm** [comment]
@fphilipe For some reason that wasn't working when I last tried it, but will check again.

**Comment by phlegx** [comment]
I use _sprockets-rails_ version **> 3.0.0** and this line:

```ruby
CompassRails.sprockets.find_asset(logical_file_path).to_s
```

instead of:

```ruby
Rails.application.assets.find_asset(logical_file_path).to_s
```

**and it works for me!**

**Comment by giedriusr** [comment]
Is this the proper way to get that logo?

**Comment by goulvench** [comment]
@phlegx's last solution works out-of-the-box, using Rails 4.2.1.

I've packaged it in a helper method in my app:

    # app/helpers/application_helper.rb
    # Returns the contents of the compiled asset (CSS, JS, etc) or an empty string
    def asset_body(name)
       (Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset(logical_file_path).to_s
    end
