### ISSUE TITLE
Upgrading from 1.7.0 to 1.8.0 in Rails changes output

### ISSUE THREAD

**Issue by brandonweiss** [fphilipe/premailer-rails#148]
I have a test that styles should be getting inlined:

```
<p style="margin: 20px 0">Hi there!</p>
```

But now they aren't:

```
<p>Hi there!</p>
```

I suspect it has something do with 56b84a3bff6eb5e0c69a7ae3561834a4cd3c6862 but I can't figure out what it is. My relevant initializers look like this:

```
Premailer::Rails.config.merge!(preserve_styles: true, css_to_attributes: true)

ActionMailer::Base.register_interceptor(ActionMailerInterceptors::MessageIDGenerator)
ActionMailer::Base.register_interceptor(ActionMailerInterceptors::EmailSubjectRailsEnvPrefixer)
ActionMailer::Base.register_interceptor(ActionMailerInterceptors::StripStylesheetLinksInterceptor)
ActionMailer::Base.register_interceptor(ActionMailerInterceptors::ClickAndOpenTrackingInjector)
ActionMailer::Base.register_interceptor(ActionMailerInterceptors::DefaultMailgunTrackingOff)
```

What am I missing?

**Comment by fphilipe** [comment]
Is this still an issue with the latest version?

**Comment by brandonweiss** [comment]
Yep, it's still an issue.

**Comment by fphilipe** [comment]
Could you throw together a minimal working example so I can look into it? #156 is possibly related to this.

**Comment by brandonweiss** [comment]
OK, here's a tiny Rails app with one test.

[demo.zip](https://github.com/fphilipe/premailer-rails/files/215951/demo.zip)

**Comment by fphilipe** [comment]
@brandonweiss premailer-rails manipulates emails upon delivery. The test case you built is failing with both premailer-rails versions. You can trigger the processing with `Premailer::Rails::Hook.perform(mail)`.
