### ISSUE TITLE
Not accounting for data-premailer='ignore'?

### ISSUE THREAD

**Issue by bdmac** [fphilipe/premailer-rails#150]
Premailer allows you to set a `data-premailer='ignore'` attr on link/style tags. I added this to a `<link type="text/css" rel="stylesheet" href="//fast.fonts.net/cssapi/[key].css" data-premailer="ignore"/>` line to leave the link tag in and load our custom fonts from fonts.com.

I was surprised to find out that our tests started breaking though because premailer-rails was making network requests to try to download that CSS file presumably so it could be inlined even though it is set to be ignored by premailer.

I'm not sure I totally understand why premailer-rails is going out of its way to do this type of work. I thought it was just hooks to run emails through premailer when sending through ActionMailer but this is doing quite a bit more than just passing it through premailer. What is the reasoning for including cache/file/asset/network request lookup bit in premailer-rails?

I forked the gem and modified the selector to match what premailer itself uses `"link[@rel='stylesheet']:not([@data-premailer='ignore'])"` so it skips links that should be ignored but without more context around this behavior I am not sure whether I should submit a PR for this or not.

**Comment by fphilipe** [comment]
premailer-rails works by reading the linked styles into a string and passing the HTML and the CSS string to premailer for inlining. premailer's CSS loading is not compatible with the asset pipeline, nor with development mode. Further, premailer-rails caches CSS files. As you see, it's not "just" a thin wrapper.

Having said that, I agree with you that the `data-premailer="ignore"` attribute should be honored. PR welcome :blush:
