### ISSUE TITLE
Premailer not running in test environment?

### ISSUE THREAD

**Issue by tsigo** [fphilipe/premailer-rails#156]
I'm having the opposite problem of https://github.com/fphilipe/premailer-rails/issues/143. We haven't limited the gem to any group in `Gemfile`, but with `remove_scripts` set to `true`, a spec that tests for the removal of a `<script>` tag in a rendered email fails.

For background, we began using the gem in [GitLab](https://gitlab.com/gitlab-org/gitlab-ce) last month (and an internal app before that - we love it!) - and recently noticed that a `script` tag was being removed from our production emails, but [these specs](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/spec/mailers/shared/notify.rb#L143-145), which check for a string in the contents of the `script` tag, weren't failing.

**Comment by tsigo** [comment]
Here's the change that fixes it for us - https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3552/diffs

But be aware that, regardless of what setting we use for `remove_scripts`, the two specs added in that diff would happily pass even when the `script` tag was being removed in development and production environments.

**Comment by fphilipe** [comment]
@tsigo Happy to hear that GitLab is using this gem. Regarding the scripts, I'm not touching the scripts at all in premailer-rails nor am I preventing the gem from running in test environments. I guess this is something related to premailer directly. Doing a quick [search for `remove_scripts`](https://github.com/premailer/premailer/search?utf8=✓&q=remove_scripts&type=Code) in premailer shows that *all* script tags are removed.

**Comment by fphilipe** [comment]
@tsigo Are you delivering the emails or simply generating them? premailer-rails hooks into ActionMailer through delivery hooks. If you want to manually trigger the processing, you can do so with `Premailer::Rails::Hook.perform(mail)`.
