### ISSUE TITLE
How do I use premailer outside a mailer in a normal controller action?

### ISSUE THREAD

**Issue by kriskhaira** [fphilipe/premailer-rails#161]
I'd like to use premailer in a controller action (not a mailer). The use case for this is to display the HTML of an email at a URL where an external app can go to the URL of the template to grab the HTML source to use in an email.

How do I do this with premailer?

**Comment by fphilipe** [comment]
See [this line] as a starter. You pass a message and it will be tweaked. You can then access the `#html_part`.

**Comment by kriskhaira** [comment]
@fphilipe I think the link wasn't linked properly in Markdown or something.

**Comment by fphilipe** [comment]
@kriskhaira 😄 sorry about that. https://github.com/fphilipe/premailer-rails/blob/master/lib/premailer/rails/hook.rb#L8

**Comment by fphilipe** [comment]
Basically you can do this:

```ruby
message = YourMailer.some_message
Premailer::Rails::Hook.perform(message)
html = message.html_part

**Comment by kriskhaira** [comment]
Hi @fphilipe. Thanks for the code sample. I ended up going with a roadie-rails solution yesterday but will give premailer a try the next time I need to do this. Thanks!
