### ISSUE TITLE
CSS with data in content: url is not inlined properly

### ISSUE THREAD

**Issue by terryyin** [fphilipe/premailer-rails#162]
I have css like:
```
#logo {
  content: asset-data-url("my.png")
}
```
The generated HTML is something like:
```
<img height="54" id="logo" style="base64,iVBORw0KGg...); content: url(data:image/png">
```

It's broken.

**Comment by fphilipe** [comment]
This is a premailer bug and should be reported at https://github.com/premailer/premailer 😊

**Comment by terryyin** [comment]
Yeah. I fixed it and my pull request has been merged. So should be part of a new gem version soon.
