### ISSUE TITLE
CSS not being loaded

### ISSUE THREAD

**Issue by RyanKim01** [fphilipe/premailer-rails#164]
Hi, I'm using devise to send out an email related to confirmation.
In confirmation_instruction.html.erb,

I load my CSS like following way and My CSS is in assets/stylesheets/components/(file name).
```
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
		<link rel="stylesheet" href="app/assets/stylesheets/components/form.css">
		<link rel="stylesheet" href="app/assets/stylesheets/components/vertical-offset.css">
		<link rel="stylesheet" href="app/assets/stylesheets/components/button.css">
  </head>
```

Then I got an error saying that 

> Premailer::Rails::CSSHelper::FileNotFound (File with URL "app/assets/stylesheets/components/form.css" could not be loaded by any strategy.):

Instead, I put below line but it still does not load CSS:
`<%= stylesheet_link_tag    "application", :media => "all" %>`

What am I doing wrong here?

**Comment by fphilipe** [comment]
Hey @RyanKim01. You have to use the `stylesheet_link_tag` for it to work. Does the `application` CSS file contain the other components that you wanted to include initially?

**Comment by fphilipe** [comment]
Is this still an issue?

**Comment by pdgonzalez872** [comment]
@RyanKim01, I agree with @fphilipe, you should use the `stylesheet_link_tag`. I would like to add that you need to use a symbol when using the helper. [Just like in the example provided](https://github.com/fphilipe/premailer-rails/blob/master/example/app/views/example_mailer/test_message.html.erb#L5). It fails when using a string, like you described above.

**Comment by danbartlett** [comment]
I just lost a few hours on this too. I don't think the docs are very clear:

> Whenever premailer-rails processes an email, it collects the URLs of all linked stylesheets (`<link rel="stylesheet" href="css_url">`)

There is no mention of `stylesheet_link_tag`, or the argument being a symbol, and so I was also trying to manually create a `<link...`, which doesn't work.

If you want me to submit an update Readme PR for this, let me know!

**Comment by fphilipe** [comment]
Sorry to hear that. I guess I assumed that in rails it's standard to use `stylesheet_link_tag`. The description explains that it parses `<link>` tags. In any case, I'll elaborate in the README.

**Comment by gavinballard** [comment]
Just chipping in in case anyone else was running into this problem - using an absolute `file://` URL in an ordinary `<link>` tag worked for me.
