### ISSUE TITLE
Color class ignored

### ISSUE THREAD

**Issue by Javix** [fphilipe/premailer-rails#167]
I tried to use `1.9.4` version in a simple mailer template as follows:
```slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    = stylesheet_link_tag    "application"
  body
    .test
      h1 Company Name
    h1 = t('.body.title')
    p = t('.body.line1')
    p = t('.body.line2', link: @url)
    p = t('.body.line3')
    p = t('.body.signature')
```
The `test`class is defined in`app/assets/stylesheets/user_mailer.scss` as follows:
```css
.test {
  color:red;
}
```

I also added the following line in `prevailer_rails.rb` initialiser:
```ruby
Premailer::Rails.config.merge!(preserve_styles: true, remove_ids: true)
```
When I tried to test it from Rails console with `letter-opener`gem, the color was not applied. What am I doing wrong ?

I am on:
```
- Ruby  2.3.0
- OS X
- Rails 4.2.5
```

**Comment by fphilipe** [comment]
The style is only inlined upon delivery. ActionMailer allows one to register an on-delivery hook. So you'd have to either `#deliver` the message or run the hook yourself as described in the [README](https://github.com/fphilipe/premailer-rails#usage) under "Usage".

**Comment by Javix** [comment]
Sure, I called the `deliver` method from Rails console:
```ruby
u = User.first
UserMailer.welcome_email(user).deliver
```
The `letter_opener` opened the generated email in the browser. The `.test` css class was not applied.

**Comment by fphilipe** [comment]
Does it work when you manually call the hook?

```ruby
u = User.first
mail = UserMailer.welcome_email(u)
Premailer::Rails::Hook.perform(mail)
mail.deliver
```

**Comment by Javix** [comment]
Nope, it produces the same result :(

**Comment by fphilipe** [comment]
Sorry, but I can't help you much more. Does it work when you don't set the custom configs? Are you sure that the stylesheet is linked correctly?

**Comment by Javix** [comment]
I figured out how to make it work. 
Here is the mailer template (not complte just for easier reading)
```slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    = stylesheet_link_tag "user_mailer"
    link href="https://fonts.googleapis.com/css?family=Open+Sans:bold" rel="stylesheet"
    link href="https://fonts.googleapis.com/css?family=Open+Sans:light" rel="stylesheet"
  body
    .header = t('base_title')
...
```
I keep `user_mailer.scss` as before, in assets/stylesheets but don't require it in `application.scss`. Instead, I added it to assets precompile in `config/initializers/assets.rb`:
```ruby
 Rails.application.config.assets.precompile += %w( user_mailer.scss )
```
Now when running it from the terminal, letter_opener opens the mail in the browser and the styles are applied.
