### ISSUE TITLE
Bad encoding of pipe char

### ISSUE THREAD

**Issue by kaluznyo** [fphilipe/premailer-rails#168]
Hi. Since premailer-rails 1.9.0 (with nokogiri) this code produce bad encoding of '|' (replace by %7). 

```ruby
Premailer::Rails::CustomizedPremailer.new("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /><a target=\"_blank\" style=\"color: #696969; text-decoration: none\" href=\"https://www.test.ch/fr/mentions-legales?auth_token=*|AUTH_TOKEN|*\">Mentions légales</a>").to_inline_css
```

Result

```ruby
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n</head>\n<body><a target=\"_blank\" style=\"color: #696969; text-decoration: none;\" href=\"https://www.eboutic.ch/fr/mentions-legales?auth_token=*%7CAUTH_TOKEN%7C*\">Mentions légales</a></body>\n</html>\n"
```

It's seem to bee since this commit https://github.com/fphilipe/premailer-rails/commit/e47869fbca9998747a94633bde3dcec6a78d5d47

Because nokogiri tranform | to %7 in 'load_html()'. And before, passing var html to super, don't produce this issue

This work fine with hpricot.

**Comment by cyrilsuzat** [comment]
I suggested an option to solve this problem : https://github.com/premailer/premailer/pull/314

**Comment by fphilipe** [comment]
I don't quite understand what the problem is. Nokogiri is correctly encoding `|` to `%7C` (not `%7` btw). Why don't you want that?

**Comment by cyrilsuzat** [comment]
The encoding is correct. The problem is that certain characters should not be encrypted because they are then processed by MailChimp.
e.g. http://stackoverflow.com/questions/8512972/preventing-nokogiri-from-escaping-characters-in-urls

**Comment by fphilipe** [comment]
Well, not encoding `|` would produce invalid HTML (just tested on W3C validator):

> Error: Bad value `http://example.com/?token=*|TOKEN|*` for attribute href on element a: Illegal character in query: `|` is not allowed.

So, I don't think that it is premailer's or premailer-rails' task to maintain MailChimp specific placeholders at the cost of invalid HTML. I suggest you add your own hook to Action Mailer that reverts those back:

```ruby
module MailChimpPlaceholderFix
  def self.delivering_email(email)
    email.html_part.body = email.html_part.body.gsub(/\*%7C(\w+)%7C\*/, '*|\1|*')
  end
end

ActionMailer::Base.register_interceptor(MailChimpPlaceholderFix)
```

Note: haven't tested the snippet above.
