### ISSUE TITLE
Embedded CSS not inlined

### ISSUE THREAD

**Issue by Cottonwoods** [fphilipe/premailer-rails#169]
Hey there, trying to use this with an email that is loaded from an html file that has all the necessary CSS written in a `<style>` tag in the `<head>`. Premailer-rails does not seem to handle this, and I would like to know if this is intended behavior or if there is an option I can set in order to inline it. Thanks.

**Comment by fphilipe** [comment]
I don't think premailer-rails supports this. The point of premailer-rails is to load CSS from the asset pipeline and pass the CSS directly to premailer, preventing it from parsing CSS out of the HTML.

Maybe you can use premailer directly, which inlines all CSS, linked ones and `<style>` tags instead when not specifying the CSS manually.

**Comment by Cottonwoods** [comment]
Ok thanks
