### ISSUE TITLE
Issue with loading CSS

### ISSUE THREAD

**Issue by cyurtbil** [fphilipe/premailer-rails#170]
I am configured premailer-rails with nokogiri and have a css file in my assets called email.css and added to my welcome.html.erb with stylesheet_link_tag. It sends the email but it doesn't recognize the stylesheets. I tried with html link tag <link... However, it gives an error for that implementation.

Can you suggest a solution or work around?

**Comment by fphilipe** [comment]
Have a look at the example app and see what you are doing differently.
