### ISSUE TITLE
Css not found when Rails.configuration.relative_url_root is '/'

### ISSUE THREAD

**Issue by nmeylan** [fphilipe/premailer-rails#171]
Hello,
I saw some issues with the same title. Hovewer, this is a real issue I had when I updated this gem to version **1.9.3**.
After several investigation, I'm sure it is due to this commit's line : https://github.com/fphilipe/premailer-rails/commit/68d1d939ec58d43e4ff0ac8bd3bbad4d0af777ed#diff-558676a8600ec15cbe6e5c48f2bcc989R23

Indeed, by default in my rails app `relative_url_root` is not `nil` and is equals to `/`
So, my asset's file_name is : `//assets/mailer.css` instead of just `mailer`

I wrote this failing spec https://github.com/nmeylan/premailer-rails/commit/ef4b2f537d1c1d618c6839bd07e04a57c2f2a9bb that demonstrate this issue

Please let me know if you want me to open a PR to fix this issue, but I think you can easily fix it by yourself.

**Comment by fphilipe** [comment]
Hey @nmeylan, thanks for reporting.

I think that you are using `relative_url_root` incorrectly. The use case is to deploy the app in a subfolder, [according to the docs](http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root). The config expects no trailing slash, so e.g. you specify `/app1`, not `/app1/` nor `app1/`. Hence, if you're using the root url, you're not supposed to set it to `/`, but instead, simply leave it at `nil`, which is the default.

What's your use case of `relative_url_root`?

That commit you pointed out actually adds support for `relative_url_root`. Before, it didn't work properly.

**Comment by nmeylan** [comment]
Hello,

you're right I made a mistake by configuring `relative_url_root` to`/`. I thought it was the default value.

Thanks for your answer and for your gem :smile:
