### ISSUE TITLE
inline style with "background-color:gold" is not getting applied

### ISSUE THREAD

**Issue by sampatbadhe** [fphilipe/premailer-rails#172]
I am applying background color as gold to table

`<table style="background-color:gold;"></table>`

But its getting removed after email is sent. In email it will removes the complete style tag

`<table></table>`

I Tried with other color like red, blue, yellow, green...etc, it works fine

`<table style="background-color:red;"></table>`

In email it shows 

`<table style="background:red;"></table>`

Any idea why it removes `background-color` style with `gold` color is not getting applied?

**Comment by fphilipe** [comment]
Why are you applying a style directly? Why not in the stylesheet?

As to why this is happening, I don't know. This gem doesn't actually inline the CSS, that is what the premailer gem does.

**Comment by sampatbadhe** [comment]
Thanks for the reply @fphilipe 

Why are you applying a style directly? Why not in the stylesheet?
> we have applied styles in stylesheet as well, but at the same time we are allowing user to apply custom styles as well. 

As to why this is happening, I don't know. This gem doesn't actually inline the CSS, that is what the premailer gem does.
> Thanks for the pointing me at right direction, I'll raise this issue to premailer gem.
