### ISSUE TITLE
stylesheet_link_tag not processing properly

### ISSUE THREAD

**Issue by unikitty37** [fphilipe/premailer-rails#173]
I have the following test_mailer/test_mail.html.erb:

```
<head>
  <%= stylesheet_link_tag 'email' %>
  <style type="text/css">
    h1 + p {
      color: #913668;
    }
  </style>
</head>
<div id="email-body">
  <h1>Test Site</h1>

  <p>Hi <%= @person.name %></p>
</div>
```

The style defined in the <head> tag is inlined correctly. However, the styles defined in email.scss are just dumped into the message's <body> tag:

```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
  </head>

  <body>
<style type="text/css">
#email-body {
font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; margin: 1em auto; padding: 2em; border-radius: 5px; max-width: 960px; min-width: 25em; width: 42em; background-color: #e16315; color: #fff;
}
</style>
    
  
  

<div id="email-body">
  <h1>Test Site</h1>

  <p style="color: #913668;">Hi Mister Test</p>

</div>
```

I can see this if I add this to a Person view:

```
<pre><%= Premailer::Rails::Hook.perform(TestMailer.test_mail(@person)) %></pre>
```

Incidentally, email.scss also fails to load at all with "ActionView::Template::Error (Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( email.css )` to `config/initializers/assets.rb` and restart your server):" unless I do this in the initialiser:

```
Rails.application.config.assets.precompile += %w( email.css )
```

Is this right? There's no mention of needing to do this in the docs. (I assume loading from outside stylesheets *is* supported, as having to copy the same styles into each email isn't exactly DRY :)

Is there a clue in the fact that the loaded stylesheet is appearing in the <body>, despite the command to load it being in the <head> section? Is the fact that it's SCSS causing the confusion

I'm using premailer 1.8.7, premailer-rails 1.9.4, nokogiri 1.6.8.1, sass 3.4.22, sass-rails 5.0.6, bootstrap-sass 3.3.6, and rails 5.0.1 with Ruby 2.3.1.

Thanks!

**Comment by fphilipe** [comment]
That's correct, the stylesheet you are using must be one that rails precompiles. That can also be your default `application.css`, which is already configured to be precompiled in `Rails.application.config.assets.precompile`. The fact that you are using SCSS makes no difference; the asset pipeline will transform that into CSS.

I didn't quite understand, does everything work as expected when your stylesheet is set up correctly? Also, try looking at the example app in this repo.

**Comment by unikitty37** [comment]
Thanks — it appears I had some structural problems with the actual HTML of the email. Adding a doctype and \<html> tag seems to have fixed it :)
