### ISSUE TITLE
Incorrect property value

### ISSUE THREAD

**Issue by NILID** [fphilipe/premailer-rails#174]
For example, I have a rule in style file:

` .logo { background-size: cover;}`

and mailer template has this string:

`<div class="logo" style="background:url(<%=image_path product.logo.url(:thumb)%>);width:200px;height:150px;" ></div>`

and then, I get a letter in which the picture is not displayed.
as, I understand that the problem in the 'initial/contain', so as to parse the code, i can see:

`<div class="m_1062825684053693123logo" style="background:url(https://ci5.googleusercontent.com/......#http://test.com/system/logos/14/thumb/pic.jpg?1474624101) no-repeat initial/contain"></div>`

and option "explore the element" of firefox shows errors "incorrect property value"
what could be the problem?

**Comment by fphilipe** [comment]
How about just setting `background-image` instead of the shorthand `background`? Does that help? If it still combines them into one illegal rule, then it's a problem with [premailer](/premailer/premailer), not premailer-rails.
