### ISSUE TITLE
High allocations and relatively slow performance

### ISSUE THREAD

**Issue by humphreybc** [fphilipe/premailer-rails#175]
I've been trying to track down some memory leaks in my app and noticed methods that use premailer to generate inline styled emails seem to be taking a long time and create a lot of allocations, which results in a fairly large memory leak over time.

Below are a couple of screenshots from Skylight, the first showing a method that uses devise_invitable to send user invitations via email, and the second is a part of my app that sends a question via email to a participant.

Are there any known issues around high allocations? Is there anything I can do to improve this? e.g. change the way I specify CSS styles, move the process to a background worker, change some premailer configuration options. Any help would be greatly appreciated!

<img width="1280" alt="screen shot 2016-11-13 at 11 47 58 am" src="https://cloud.githubusercontent.com/assets/1124253/20243720/edabc296-a9b7-11e6-99dd-88f75dc99954.png">

<img width="1280" alt="screen shot 2016-11-13 at 3 42 58 pm" src="https://cloud.githubusercontent.com/assets/1124253/20243722/f4ec1fe2-a9b7-11e6-9758-005d19a67789.png">

**Comment by fphilipe** [comment]
premailer-rails only passes CSS from your rails app down to [premailer](/premailer/premailer). To be honest I've never profiled the memory allocation, so I don't know whether it is happening in premailer-rails or premailer. Depending on how you've configured your app, it could also be the asset pipeline compiling the CSS. How does your rails asset config look like?

Anyhow, you should definitely not be sending emails from within a request. Regardless of premailer-rails, sending emails is slow and should thus be done in a background process or a separate thread.

**Comment by humphreybc** [comment]
Hey @fphilipe thanks for your reply. Yes, agree that the mailer should be in a background process. It's not a very frequent action (admin invitations) so I could live with it blocking the thread for a while. I've since moved mailers to a background queue to see if that helps, however I'm still seeing very high allocations on this method in Skylight – average time is 530ms and average allocations is 392,666. Perhaps it has something to do with how premailer handles caching?

Here's `config/environments/production.rb` (comments removed):

```
Rails.application.configure do
  config.cache_classes = true
  config.eager_load = true
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true
  config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?
  config.assets.js_compressor = :uglifier
  config.assets.compile = false
  config.force_ssl = true
  config.log_level = :debug
  config.log_tags = [ :request_id ]
  config.action_mailer.perform_caching = false
  config.i18n.fallbacks = true
  config.active_support.deprecation = :notify
  config.log_formatter = ::Logger::Formatter.new

  if ENV["RAILS_LOG_TO_STDOUT"].present?
    logger           = ActiveSupport::Logger.new(STDOUT)
    logger.formatter = config.log_formatter
    config.logger = ActiveSupport::TaggedLogging.new(logger)
  end

  config.active_record.dump_schema_after_migration = false
  config.action_mailer.default_url_options = { host: Figaro.env.domain }
end
```

And here's `config/initializers/assets.rb` (comments removed):

```
Rails.application.config.assets.version = '1.0'
```

Appreciate your help!

**Comment by fphilipe** [comment]
I highly doubt that premailer-rails is allocating that many objects, unless it is triggering the asset pipeline to compile something. It could be, depending on how big and complex your stylesheet is, that premailer itself or one of its dependencies is allocating that many objects. You could try profiling it e.g. with https://github.com/SamSaffron/memory_profiler.

**Comment by sevab** [comment]
Hi @humphreybc we are seeing a similar memory leak with our app's mailer. Did you find a culprit of yours?
