### ISSUE TITLE
String html to inline css

### ISSUE THREAD

**Issue by alexey** [fphilipe/premailer-rails#176]
Hi, 

Is possible to somehow have string "premailed",
I have raw html in string and need convert its css(all css rules defined in head section, no external css files) into inline css.

**Comment by fphilipe** [comment]
Sorry, I don't understand your question 😕 CSS can only be applied to HTML tags, so you need to wrap you string in a tag.

**Comment by alexey** [comment]
Sorry, I'll give an example.
I have following html in string(very simplified for example):
```html
<html>
  <head>
    <style>
        .myclass{
            color:red;
        }
    </style>
  </head>
  <body>
    <p class="myclass">text</p>
   </body>
</html>
```

I am looking if possible to make css to inline css conversion of it with premailer gem

**Comment by fphilipe** [comment]
Are you using rails at all? Otherwise you can just use [premailer](/premailer/premailer) directly.

**Comment by alexey** [comment]
I do use rails, but you are totally right, Ill use premailer directly 

Thank you for the clue !
