### ISSUE TITLE
Problem with gmaps static images url escaping

### ISSUE THREAD

**Issue by romaind** [fphilipe/premailer-rails#178]
Hi everyone,

First of, thanks for the gem, it's pretty cool.
I have an issue with this gem when using it on an email with a static google map with path option.
To the path option of the image url, I pass something that goes like:
`path=something%7Cenc:blabla....[blabla...`
this `enc:....` part being sent by google at some point.

But, when passed through `premailer-rails` this part of the map url becomes `path=something%7Cenc:blabla....%5Bblabla...`

This preventing the image to display in my email.

I've dug a lot and found that nokogiri (and hpricot too I think) are causing this in `customized_premailer.rb` file when doing:
```
doc = load_html(html)
super(doc.to_s, options)
```

my url is correct in `html`
but that's when doing `to_s` on `doc` (a `Nokogiri::HTML::Document` if I remember) that my `[` becomes a `%5B`.

From what I see `doc.to_s` and `html` are a lot similar (html strings) besides my problem (and maybe other things that I don't know)

My question is: do we really need to use `doc.to_s`, couldn't we just do `super(html, options)` which totally works in my case?

**Comment by fphilipe** [comment]
Hey, have a look at the [config options](http://www.rubydoc.info/gems/premailer/Premailer%3Ainitialize) for `Premailer`.

Maybe it helps by setting `escape_url_attributes` to `false`, which by default is `true`.

You can set this option in premailer-rails as explained [here](http://www.rubydoc.info/gems/premailer/Premailer%3Ainitialize).

Other than that, I don't think there's a way to control this. Maybe ask directly at the premailer gem.
