### ISSUE TITLE
NetworkLoader requesting asset from incorrect URL

### ISSUE THREAD

**Issue by agis-** [fphilipe/premailer-rails#179]
In a Rails 4.2 app (sprockets 2), falling back to the NetworkLoader class doesn't work as expected.

In the view I do:

```erb
<%= stylesheet_link_tag "email/template" %>
```

which in production is accessible through `http://www.example.com/assets/email/template.css`. 

However, after deliberately removing the file from the filesystem (`public/assets` and `tmp/cache/sass`) in order to hit the `NetworkLoader`, the file is requested from `http://www.example.com/stylesheets/email/template.css` which is incorrect.

The asset helper however, produces the correct URL:

```ruby
Loading production environment (Rails 4.2.7.1)
irb(main):001:0> helper.stylesheet_link_tag("email/template")
=> "<link rel=\"stylesheet\" media=\"screen\" href=\"//www.example.com/assets/email/template-debe83adf12cb6234da6fc14727e9663.css\" />"
```

Is this behavior expected?

**Comment by fphilipe** [comment]
What's your asset host config?

**Comment by agis-** [comment]
@fphilipe This was actually due to the asset pipeline expecting a `public/assets` folder to be present while it wasn't. Closing this as a non-issue. Thanks!
