### ISSUE TITLE
Setting the Base URL

### ISSUE THREAD

**Issue by eric1234** [fphilipe/premailer-rails#181]
The pre-mailer has the option to [configure a base_url](https://github.com/premailer/premailer/blob/master/lib/premailer/premailer.rb#L156) but I don't see how the Rails integration works with that and am getting broken images. Perhaps does this plugin need to read the default url options of ActionMailer and construct a base URL from that?

**Comment by getninjaN** [comment]
Not sure if you've solved this or not. You probably have.

I've been looking for an answer today and found that you can add
```ruby
if Rails.configuration.action_mailer.asset_host.present?
  Premailer::Rails.config.merge!(base_url: Rails.configuration.action_mailer.asset_host)
end
```
to `config/initializers/premailer_rails.rb` and this should make it guud.

**Comment by fphilipe** [comment]
@eric1234 not sure why you'd need that. When using the asset pipeline with an asset host the image urls should already be absolute. In any case, @getninjaN's suggestion would be the way to set the config.

**Comment by eric1234** [comment]
The images being included on the e-mail are stored images (served from Dragonfly) not asset pipeline images. I'll give @getninjaN's method a try as I should be circling back to this project this week. Thanks for the feedback!

**Comment by eric1234** [comment]
I have confirmed @getninjaN's method did work for my needs. Perhaps something Premailer-rails should be doing for us. I think assuming all assets are going through the asset pipeline assumes too much.

**Comment by fphilipe** [comment]
@eric1234 glad it worked out.

My take is that, if the asset is coming from the app, it'll work because Rails takes care of transforming a relative path to an absolute one. If you're including a remote asset, you should specify the absolute path.
