### ISSUE TITLE
Why preserve_styles: true?

### ISSUE THREAD

**Issue by franzliedke** [fphilipe/premailer-rails#183]
The initializer example in the README suggests to use the `preserve_styles: true` config option. I wonder why?

This seems to result in the `<style>` tags in the header staying intact. But I suppose that after inlining, these could be removed... Or is that a problem with some email clients?

**Comment by fphilipe** [comment]
@franzliedke certain things such as media queries and hover states won't be inlined. Leaving the `<style>` there allows clients that read external stylesheets to still apply those things.

**Comment by franzliedke** [comment]
Great, thanks for the explanation.
