### ISSUE TITLE
Avoiding <style> tag

### ISSUE THREAD

**Issue by eric1234** [fphilipe/premailer-rails#184]
Even through [`preserve_styles` defaults to false](https://github.com/premailer/premailer/blob/master/lib/premailer/premailer.rb#L196) I am still seeing the styles from my `stylesheet_link_tag` in a `style` section in the e-mail. The styles are correctly inlined but they are also in a `style` tag. This causes the e-mail to be much bigger as a bunch of styles are included (not just those inlined). This causes Gmail to display as `[message clipped]`. How can I get just the inlined ones?

**Comment by eric1234** [comment]
Closing this as I realized it was due to unused styles. Evidently they are preserved by premailer in a style tag. My assumption was that any styles that could not be inlined were dropped. This assumption was incorrect.

**Comment by bborn** [comment]
Any chance of merging this (https://github.com/soundasleep/premailer-rails/commit/e4a0e7f1b803f08feb03fec5eda96a5b61c68e3d) in?

**Comment by fphilipe** [comment]
Probably not.

Maybe @eric1234's explanation can help you to reduce your message size:

> Closing this as I realized it was due to unused styles. Evidently they are preserved by premailer in a style tag. My assumption was that any styles that could not be inlined were dropped. This assumption was incorrect.
