### ISSUE TITLE
Text file attachment error

### ISSUE THREAD

**Issue by DSalko** [fphilipe/premailer-rails#185]
When trying to send email with txt file attached, getting 

`Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8`

works fine without Premailer. Any suggestions?

**Comment by fphilipe** [comment]
This is likely due to premailer-rails adding a `text/plain` part to your email based on the contents of the HTML email part. Does it work when you set the config `generate_text_part: false`?

**Comment by DSalko** [comment]
This doesn't help. Although, I worked it around by ensuring that txt file is in UTF-8 before attaching.
thank you.
