### ISSUE TITLE
Make FileSystemLoader path configurable

### ISSUE THREAD

**Issue by stanhu** [fphilipe/premailer-rails#194]
Currently the `FileSystemLoader` attempts to read from the current `public/` directory for assets, but if the working directory isn't `Rails.root` this will fail and cause the premailer-rails gem to quietly try the other loaders.

We are currently working around this by adding a symlink to the right `public/` directory, but it seems better if either the `FileSystemLoader` used `#{Rails.root}/public` or allowed this to be configured.

**Comment by fphilipe** [comment]
Sounds reasonable. I'll gladly accept a PR 😉 

One question though, what are the use cases for running rails not from the rails root?

**Comment by stanhu** [comment]
In GitLab, we run Sidekiq from another working directory (`/var/opt/gitlab/gitlab-rails/working`) just in case one of the jobs needs to write temporary data to the current directory.

I've submitted #195 to use `Rails.root` if available.

**Comment by stanhu** [comment]
This affected a number of users (see full context in https://gitlab.com/gitlab-org/gitlab-ce/issues/34231). Because we recently disabled asset pipeline compilation, users found that the network loader attempted to fetch HTTPS endpoints that presumably had needed some custom certificates, which failed because the default `Net::HTTP` settings may not be adequate. It sounds to me that this gem should also support custom SSL options as well.
