### ISSUE TITLE
Could not find css_parser-1.6.0 in any of the sources

### ISSUE THREAD

**Issue by svensson-david** [fphilipe/premailer-rails#198]
Hello!
I've added premailer-rails as well as nokogiri to my gemfile and run bundle install. Bundler says everything installed but when trying to run `rails server` I get the following response:

``Could not find css_parser-1.6.0 in any of the sources``
``Run `bundle install` to install missing gems.``

Running bundle install again does not help. Adding css_parser to gemfile does not help. If I remove premailer-rails from the gemfile the server starts again.

Is this a known problem? Do you have any ideas on solutions?

rails 5.1.4
ruby 2.4.1

**Comment by fphilipe** [comment]
Did you run `bundle install`? What's the content of your `Gemfile.lock`? Does it include `css_parser`?

**Comment by svensson-david** [comment]
Closing this
It seems to have been an overall PATH issue which multiple rails versions coming into play.
Bundle install did work and the gemfile did included css_parser but the correct versions were not used in any case.
