### ISSUE TITLE
NoMethodError: undefined method `assets_manifest'

### ISSUE THREAD

**Issue by derekwheel** [fphilipe/premailer-rails#213]
After upgrading to premailer-rails >= 1.10.0, I encounter the following error unless 'sprockets/railtie' is explicitly required:
```
NoMethodError: undefined method `assets_manifest' for #<Api::Application:0x0000000003c40fb0>
  from premailer/rails/css_loaders/asset_pipeline_loader.rb:27:in `asset_pipeline_present?'
  from premailer/rails/css_loaders/asset_pipeline_loader.rb:8:in `load'
  from premailer/rails/css_helper.rb:47:in `block in load_css'
  from premailer/rails/css_helper.rb:46:in `each'
  from premailer/rails/css_helper.rb:46:in `load_css'
  from premailer/rails/css_helper.rb:38:in `load_css_with_cache'
  from premailer/rails/css_helper.rb:18:in `css_for_url'
  from premailer/rails/css_helper.rb:13:in `block in css_for_doc'
  from premailer/rails/css_helper.rb:13:in `map'
  from premailer/rails/css_helper.rb:13:in `css_for_doc'
  from premailer/rails/customized_premailer.rb:14:in `initialize'
  from premailer/rails/hook.rb:97:in `new'
  from premailer/rails/hook.rb:97:in `premailer'
  from premailer/rails/hook.rb:86:in `generate_text_part'
  from premailer/rails/hook.rb:62:in `generate_alternative_part'
  from premailer/rails/hook.rb:50:in `generate_html_part_replacement'
  from premailer/rails/hook.rb:24:in `perform'
  from premailer/rails/hook.rb:8:in `perform'
```
Explicitly requiring 'sprockets/railtie' in my app fixes this, but if this is a dependency of premailer-rails, it seems like it should be required here. I have created a PR (https://github.com/AnrichVS/premailer-rails/pull/1) against the branch in https://github.com/fphilipe/premailer-rails/pull/212. It appears that PR was closed, is there another approach to fix this issue?

**Comment by fphilipe** [comment]
Well, first of all, are you using rails? If you are, then sprockets should already be loaded, I'd guess. If not, is this in development?

**Comment by derekwheel** [comment]
This happens in development and production environments, and in a worker process that doesn't need the asset pipeline loaded (this might also be true in an API project, or really Rails app that decides not to load 'sprockets/railtie'). In this case, Rails is loaded, Rails::Application is available, but assets_manifest is not since 'sprockets/railtie' was never loaded.
Currently ```AssetPipelineLoader#asset_pipeline_manifest``` looks like this:

```Ruby
def asset_pipeline_present?
  defined?(::Rails) && ::Rails.application && ::Rails.application.assets_manifest
end
```

What if another check was added to make sure Sprockets is loaded?
```Ruby
def asset_pipeline_present?
  defined?(::Rails) && defined?(::Sprockets) &&
    ::Rails.application && ::Rails.application.assets_manifest
end
```
This would solve my issue and I'd be happy to send a PR your way if this works for you.

**Comment by fphilipe** [comment]
> What if another check was added to make sure Sprockets::Railtie is loaded?

In that case you wouldn't get an error and the emails would not get styled. I'd rather have this error telling you that something is missing.

Just to clarify, do you want to use the asset pipeline for premailer-rails or not?

**Comment by derekwheel** [comment]
With my proposed change (checking that Rails.applications responds to :assets_manifest), the emails do get styled, as they come from the filesystem. This seems weird, because of the Rails.config.strategies ordering the filesystem should get loaded first and returned by CSSHelper#load_css before. This would imply I should not see the asset pipeline strategy being invoked. I will take a look and see what's going on there.
