### ISSUE TITLE
Generation of text part missing a line break after <pre> or <blockquote>

### ISSUE THREAD

**Issue by jmuheim** [fphilipe/premailer-rails#215]
I'm using `<pre>` and `<blockquote>` in my HTML mail:

![image](https://user-images.githubusercontent.com/1814983/35149242-a67ae75a-fd15-11e7-8c80-1a9d16c68519.png)

The generated plain text version is missing a 2nd line break after this element though:

<img width="523" alt="nomethoderror_at__rails_mailers_trial_session_request_mailer_thank_you_email_html" src="https://user-images.githubusercontent.com/1814983/35149300-e0143b38-fd15-11e7-9460-34d3fd9637df.png">

How can this be added?

And is there a way to configure how the plain text version looks? For example, I'd like H1 to become

    This is H1
    ==========

instead of

    **********
    This is H1
    **********

Thank you.

**Comment by fphilipe** [comment]
premailer-rails is just a wrapper around [premailer](/premailer/premailer), which is responsible for the plain text generation. I suggest you open an issue over there.
