### ISSUE TITLE
Works with Regular Mailer, not with custom

### ISSUE THREAD

**Issue by justindunn** [fphilipe/premailer-rails#223]
Hello! I'm using maildown and premailer-rails, I have the normal rails mailer (app/mailers/mailer.rb) and I have a custom mailer that inherits from that mailer notification_mailer.rb (app/mailers/notification_mailer.rb) ```class NotificationMailer < Mailer```

All the views are in the app/views/mailer directory and the layout is rendering fine for each, just no html is parsed into inline css for any emails coming from notification_mailer.rb, only mailer.rb.
Do I have to enable it differently for a custom mailer file?

**Comment by fphilipe** [comment]
All emails are processed. Are you sure the CSS is linked in the email?

You can try running the hook manually to see if the parsing works. From the README:

> Emails are only processed upon delivery, i.e. when calling #deliver on the email, or when previewing them in rails. If you wish to manually trigger the inlining, you can do so by calling the hook:
>
> ```ruby
> mail = SomeMailer.some_message(args)
> Premailer::Rails::Hook.perform(mail)
> ```

**Comment by justindunn** [comment]
When I look at the emails in mailhog, I see that the mails sent from mailer.rb have no stylesheet link in the rendered html of the email and all styles are inlined, but with notification_mailer.rb, the stylesheet 
link is still in the source of the email and no inline styles have been applied. 

<img width="1137" alt="screen shot 2018-07-12 at 11 44 46 am" src="https://user-images.githubusercontent.com/1703225/42644265-2822be54-85c9-11e8-99c6-b344933249f1.png">
<img width="1088" alt="screen shot 2018-07-12 at 11 45 36 am" src="https://user-images.githubusercontent.com/1703225/42644266-283416f4-85c9-11e8-8a4f-3c8eddedf7f1.png">

**Comment by fphilipe** [comment]
Can you please try the snippet I posted above and inspect the body of the mail afterwards? If it's still not inlined it means that something is off with your stylesheet link.
