### ISSUE TITLE
Fonts are falling back

### ISSUE THREAD

**Issue by nick-vention** [fphilipe/premailer-rails#224]
Importing fonts as so:
```
@font-face {
  font-family: 'Lato';
  src: asset-url('Lato-Regular.eot');
  src: asset-url('Lato-Regular.eot?#iefix') format('embedded-opentype'),
        asset-url('Lato-Regular.woff') format('woff'),
        asset-url('Lato-Regular.ttf') format('truetype');
}

html, body {
  font-family: 'Lato', 'Helvetica Neue', Helvetica, Arial, sans-serif;
  font-size: 14px;
}

```

The font shows up before the email is sent, when looking at the HTML file, however, when viewing the email in a client the font falls back to Arial. I have tried both Apple Mail and Gmail. The font shows up in Apple mail if premailer is skipped.

**Comment by fphilipe** [comment]
You might want to ask over at premailer (this is just the Rails integration).

Make sure that premailer is configured not to remove the original CSS. Then I think it should work.

**Comment by eveevans** [comment]
@ghost any  news ? I'm having the same problem.
