### ISSUE TITLE
Doesn't include `grid-template-columns` in inline CSS

### ISSUE THREAD

**Issue by Kashspike** [fphilipe/premailer-rails#228]
Working with premailer-rails, i came across the `grid-template-columns` & `grid-gap` property which it ignores on inline css on rendering in Gmail. 

```
.event-section {
      padding: 30px 0 20px;
      border-top: 1px solid $light-gray;
      display: grid;
      width: 100%;
      grid-template-columns: repeat(auto-fill, minmax(170px, max-content));
      grid-gap: 50px;
}
```

Output in Gmail:

`<div class="m_-3341747333242917963event-section" style="border-top-width:1px;border-top-color:#f2f2f2;border-top-style:solid;display:grid;width:100%;padding:30px 0 20px">`

Anyone knows why is this happening??

**Comment by fphilipe** [comment]
This is related to premailer, not premailer-rails, which is just about the rails integration. Please report this over at [premailer](https://github.com/premailer/premailer).
