### ISSUE TITLE
rails 6 upgrade

### ISSUE THREAD

**Issue by phoet** [fphilipe/premailer-rails#231]
i'm currently upgrading our app to rails 6 beta1

since we are using premailer-rails, i created a fork that allows using it with rails > 5

if you are interested in merging the changes here, please ping me.

find the branch here https://github.com/penseo/premailer-rails/pull/1

**Comment by fphilipe** [comment]
Thanks. I've bumped the ruby version [here](https://github.com/fphilipe/premailer-rails/commit/39f802f5c0a2a11762efa024a9300eea44a87009), which causes Travis CI to run the specs for rails master ([they're passing](https://travis-ci.org/fphilipe/premailer-rails/jobs/486935039)).

With this you should be able to point to this repo in your project without having to fork it. Once rails 6 is out, I'll change the gemspec to require rails < 7 so it can pick up the final rails 6 version.

**Comment by phoet** [comment]
@fphilipe unfortunately this is not correct!

you still have a version requirement of rails < 6 in the gemspec which makes it necessary to fork it!

see this change of the PR https://github.com/penseo/premailer-rails/pull/1/files#diff-122c0cc5159b5325eba36306429d40b2R25

**Comment by fphilipe** [comment]
@phoet I think you're mistaken. This is a feature of semantic versioning (see [spec item 11](https://semver.org/#spec-item-11)):

> When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version. Example: 1.0.0-alpha < 1.0.0.

That is the reason why bundler was able to resolve the requirements in [this build](https://travis-ci.org/fphilipe/premailer-rails/jobs/486935039). If that were not the case, it would have failed to install the gems.

**Comment by phoet** [comment]
ah, TIL!

🤔 bundler must have choked on this dependency for another reason then...

thanks for the linked info.
