### ISSUE TITLE
Didnt't work immediately with Rails version 5.0.2

### ISSUE THREAD

**Issue by LemonAndroid** [fphilipe/premailer-rails#238]
Hey,

After following the instructions in the Readme, I tried running a test case and didn't notice any inlining.

Kind regards
MAK

**Comment by fphilipe** [comment]
Hi @LemonAndroid. I'm not sure if you're asking for help or just sharing your experience. In either case, I'll need more information.

**Comment by LemonAndroid** [comment]
I'm just sharing my experience.

I'm now using premailer w/o premailer-rails.

Philipe Fatio <notifications@github.com> schrieb am Di., 12. März 2019 um
19:30 Uhr:
