### ISSUE TITLE
Inlined stylesheet is incorrectly encoded

### ISSUE THREAD

**Issue by dlouzan** [fphilipe/premailer-rails#246]
Hello, I'm working on an MR in gitlab for migrating some of the mailers to use premailer for html emails but I'm having an issue where premailer is entity encoding some of my stylesheet rules when I inline them.

I've tried this with several premailer-rails versions, including the latest release 1.10.3.

There's some stylesheet rules that I need to inline in the header of the html email (particularly using the `@media` tag that seems not properly supported by premailer). One of them includes a direct descendant rule, and premailer is entity-encoding it to `&gt;` in the inlined style, even if I tell premailer to ignore it:

```haml
    %style{ type: 'text/css', 'data-premailer': 'ignore' }
      = asset_to_string('mailer_client_specific.css').html_safe
```

```ruby
  def asset_to_string(name)
    app = Rails.application
    if Rails.configuration.assets.compile
      app.assets.find_asset(name).to_s
    else
      controller.view_context.render(file: File.join('public/assets', app.assets_manifest.assets[name]))
    end
  end
```

`mailer_client_specific.css` has a rule like:

```css
  table.wrapper > tbody > tr > td {
    ...
  }
```

And this is incorrectly generated by premailer in the final html as:

```css
  table.wrapper &gt; tbody &gt; tr &gt; td {
    ...
  }
```

As soon as I remove premailer processing this works as intended:

```
      mail(bcc: recipients,
           subject: pipeline_subject(status),
           skip_premailer: true) do |format|
        ...
```

You can take a look at our code in https://gitlab.com/gitlab-org/gitlab/merge_requests/17699

Any ideas? is this a bug in premailer or am I doing anything wrong? Thanks!

The inspiration for inlining the stylesheet was taken from:

- https://stackoverflow.com/questions/10386923/how-to-inline-css-when-using-the-rails-asset-pipeline
- https://stackoverflow.com/questions/3028033/in-haml-on-ruby-on-rails-how-to-use-the-sass-filter

**Comment by dlouzan** [comment]
Maybe related: https://github.com/premailer/premailer/issues/355

**Comment by dlouzan** [comment]
This seems to be the same as https://github.com/premailer/premailer/issues/353, sadly no answer in that ticket since 2017 :-(

**Comment by fphilipe** [comment]
Closing this as this is clearly an issue on premailer's side. Thanks for reporting though!
