### ISSUE TITLE
bump premailer version

### ISSUE THREAD

**Issue by rex-remind101** [fphilipe/premailer-rails#254]
This gem relies on a very old version of premailer, namely one that includes hpricot whose `hpricot_slate_method_added` magic causes issues with sorbet. Please update this dependency to use a more recent version of premailer.

**Comment by fphilipe** [comment]
This is the dependency definition:

https://github.com/fphilipe/premailer-rails/blob/v1.11.1/premailer-rails.gemspec#L24

premailer is currently at 1.11.1. If you do a fresh install of premailer-rails, it will install the latest premailer version. Thus, you should be able to simply run `bundle update premailer` to get a newer version of premailer in your project.

**Comment by rex-remind101** [comment]
Thank you for the quick and educational reply, new ecosystem I'm working in.
