### ISSUE TITLE
skip_premailer: false does not work

### ISSUE THREAD

**Issue by erikaxel** [fphilipe/premailer-rails#257]
Hi,

I have situation where i want to conditionally use premailer. However, when setting skip_premailer to false, it still skips premailer, it seems like it only checks if the parameter is there, not what the actual boolean value is.

I have a workaround which is to not set the parameter when I want premailer, but that involves conditional adding keys to a hash which is quite ugly.

**Comment by fphilipe** [comment]
This is expected, see https://github.com/fphilipe/premailer-rails/issues/113.

I'm afraid you'll have to stick to the workaround 😊
