### ISSUE TITLE
Webpack and Sidekiq not sending emails on non-test environments

### ISSUE THREAD

**Issue by onesneakymofo** [fphilipe/premailer-rails#263]
I am trying to move all of our assets over to Webpacker/Webpack. I have gotten this working locally thanks to #232, but whenever I ship to our staging environment, our Sidekiq fails to deliver our emails. 

All of our Sidekiq servers are on separate instances from our web servers. As such, since Sidekiq has no awareness of Webpacker/Webpack, I get the following error when trying to send emails:

```
ActionView::Template::Error: Webpacker can't find mailer.css in 
/opt/project/public/packs/manifest.json. 
```

Any guidance is appreciated.

**Comment by fphilipe** [comment]
Closing as stale.
