### ISSUE TITLE
Support CSSParser option rule_set_exceptions

### ISSUE THREAD

**Issue by JasonBarnabe** [fphilipe/premailer-rails#273]
Allow passing the option rule_set_exception to CSSParser per https://github.com/premailer/css_parser/issues/125.

**Comment by markedmondson** [comment]
If https://github.com/premailer/premailer/pull/419 gets merged then it'll be automatically supported through https://github.com/fphilipe/premailer-rails/blob/main/lib/premailer/rails/customized_premailer.rb#L11 using `Premailer::Rails.config.merge!(rule_set_exceptions: false)`

**Comment by fphilipe** [comment]
Closing as this is possible as @markedmondson explained.
