### ISSUE TITLE
Beware asset_host that begin with "//" and not "http:// or https://"

### ISSUE THREAD

**Issue by i8ramin** [fphilipe/premailer-rails#69]
This is just an FYI that if your asset_host is defined without the "http:" part, then premailer will fail to load the css file in CSSLoaders::request_and_unzip.

We define our asset_host w/o the http part so that we don't have to deal with http/https warnings. We fixed this issue like so in our env config files:

``` ruby
# Enable serving of images, stylesheets, and JavaScripts from an asset server
config.action_controller.asset_host = "//#{ENV['CLOUDFRONT_URL']}"

# set action_mailer asset_host for assets in emails
config.action_mailer.asset_host = "http:" + config.action_controller.asset_host
```

**Comment by cameliaben** [comment]
Excellent! Really useful!
