### ISSUE TITLE
Undefined method "force_encoding" in css_helper

### ISSUE THREAD

**Issue by nneal** [fphilipe/premailer-rails#99]
UPDATE: Apparently I forgot to precompile this asset which explains why css helper couldn't find it. A more descriptive error when not found or an empty string returned could be a nice improvement. i can write a PR for this if you like the idea

---

I'm getting an error within premailer-rails when trying to send emails in my staging environment. It's working fine in dev. 

My staging env is an Ubuntu server. Looks like the issue is that `load_css` is returning an array. It appears that the css is never found which would cause the block in `load_css` to return an array. 

We're using cloudfront as an asset host, and I'm guessing that's the source of the problem.

Any ideas? I'm digging into this myself, too, but wanted to see if there were any quick fixes before I do a deep dive.

Stack trace:

```
premailer/rails/css_helper.rb:19:in `block in css_for_doc'
  urls.map { |url| load_css(url).force_encoding('UTF-8') }.join("\n")
premailer/rails/css_helper.rb:19:in `map'
  urls.map { |url| load_css(url).force_encoding('UTF-8') }.join("\n")
premailer/rails/css_helper.rb:19:in `css_for_doc'
  urls.map { |url| load_css(url).force_encoding('UTF-8') }.join("\n")
premailer/rails/customized_premailer.rb:15:in `initialize'
  options = @options.merge(css_string: CSSHelper.css_for_doc(doc))
premailer/rails/hook.rb:80:in `new'
  @premailer ||= CustomizedPremailer.new(html_part.decoded)
premailer/rails/hook.rb:80:in `premailer'
  @premailer ||= CustomizedPremailer.new(html_part.decoded)
premailer/rails/hook.rb:76:in `generate_text_part'
  body: premailer.to_plain_text)
premailer/rails/hook.rb:57:in `generate_alternative_part'
  part.add_part(generate_text_part)
.........
```

**Comment by nicocharlery** [comment]
For me, the issue was a`<link rel="stylesheet" href="style.css" />` present in the file that caused the issue. `style.css` was leading to nowhere.

**Comment by griff** [comment]
I just had the same problem as @bokay. It might make sense to check for non-existing css and raise a more descriptive error.
